# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20170307_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionlikes',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.AlterField(
            model_name='submission',
            name='app_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
