# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170307_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='member4',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='member5',
        ),
        migrations.AlterField(
            model_name='submission',
            name='app_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
