# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170313_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='app_type',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='ip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
