# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170314_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='session_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
