# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20170316_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
