# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20170316_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
